### ISSUE TITLE
Does not work on Firefox v47.0

### ISSUE THREAD

**Issue by stardiviner** [brcontainer/stack-exchange-notifications#20]
It shows:
```
Response error:
You must be logged to https://stackexchange.com/ 
```
I did logged in Stack Exchange.

**Comment by brcontainer** [comment]
@stardiviner Firefox 47 don't support all features from extension 1.x.x version, you should be using a old version.

This is a bug already solved in new versions, but unfortunately the extension uses ["`web_accessible_resources`"](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/web_accessible_resources), that requires Firefox 48. Then only updating Firefox.

**Comment by stardiviner** [comment]
This extension still does not work. After I installed Firefox nightly "v59"
I'm using Arch Linux system.

**Comment by stardiviner** [comment]
I try to follow the README debug steps.
I tried:
```
StackExchangeNotifications.setAchievements(300);
StackExchangeNotifications.update();
```
in Console.
But got error:
```
ReferenceError: StackExchangeNotifications is not defined
```

**Comment by brcontainer** [comment]
@stardiviner Firefox?

**Comment by stardiviner** [comment]
![screenshot_20180108_142716](https://user-images.githubusercontent.com/378699/34660790-18dc69e8-f480-11e7-96d4-f94c29379086.png)
Here is the screenshot of trying:
```javascript
StackExchangeNotifications.setAchievements(300);
StackExchangeNotifications.update();
```

**Comment by stardiviner** [comment]
And here is the js code which I open
```
No matching message handler for the given recipient. MessageChannel.jsm:703
	_handleMessage/</< resource://gre/modules/MessageChannel.jsm:703:11
```
The source code:

``javascript
/**
   * Handles dispatching message callbacks from the message brokers to their
   * appropriate `MessageReceivers`, and routing the responses back to the
   * original senders.
   *
   * Each handler object is a `MessageReceiver` object as passed to
   * `addListener`.
   *
   * @param {Array<MessageHandler>} handlers
   * @param {object} data
   * @param {nsIMessageSender|{messageManager:nsIMessageSender}} data.target
   */
  _handleMessage(handlers, data) {
    if (data.responseType == this.RESPONSE_NONE) {
      handlers.forEach(handler => {
        // The sender expects no reply, so dump any errors to the console.
        new Promise(resolve => {
          resolve(handler.receiveMessage(data));
        }).catch(e => {
          Cu.reportError(e.stack ? `${e}\n${e.stack}` : e.message || e);
        });
      });
      data = null;
      // Note: Unhandled messages are silently dropped.
      return;
    }

    let target = new MessageManagerProxy(data.target);

    let deferred = {
      sender: data.sender,
      messageManager: target,
      channelId: data.channelId,
      respondingSide: true,
    };

    let cleanup = () => {
      this.pendingResponses.delete(deferred);
      target.dispose();
    };
    this.pendingResponses.add(deferred);

    deferred.promise = new Promise((resolve, reject) => {
      deferred.reject = reject;

      this._callHandlers(handlers, data).then(resolve, reject);
      data = null;
    }).then(
      value => {
        let response = {
          result: this.RESULT_SUCCESS,
          messageName: deferred.channelId,
          recipient: {},
          value,
        };

        target.sendAsyncMessage(MESSAGE_RESPONSE, response);
      },
      error => {
        if (target.isDisconnected) {
          // Target is disconnected. We can't send an error response, so
          // don't even try.
          if (error.result !== this.RESULT_DISCONNECTED &&
              error.result !== this.RESULT_NO_RESPONSE) {
            Cu.reportError(Cu.getClassName(error, false) === "Object" ? error.message : error);
          }
          return;
        }

        let response = {
          result: this.RESULT_ERROR,
          messageName: deferred.channelId,
          recipient: {},
          error: {},
        };

        if (error && typeof(error) == "object") {
          if (error.result) {
            response.result = error.result;
          }
          // Error objects are not structured-clonable, so just copy
          // over the important properties.
          for (let key of ["fileName", "filename", "lineNumber",
                           "columnNumber", "message", "stack", "result"]) {
            if (key in error) {
              response.error[key] = error[key];
            }
          }
        }

        target.sendAsyncMessage(MESSAGE_RESPONSE, response);
      }).then(cleanup, e => {
        cleanup();
        Cu.reportError(e);
      });
  },
```

**Comment by brcontainer** [comment]
@stardiviner this error:

> No matching message handler for the given recipient. MessageChannel.jsm:703
> 	_handleMessage/</< resource://gre/modules/MessageChannel.jsm:703:11

is a generic error, note that in the console you will see messages from all add-ons, you may also have loaded the add or reloaded it, anyway in your image I do not see the first error that you reported:

> ReferenceError: StackExchangeNotifications is not defined

---

I tried load from Debug, see result:

![debug firefox](https://user-images.githubusercontent.com/4368952/34693382-72e574d2-f4aa-11e7-968e-7e19860f08e7.png)

Note, score show "1" for any score, inbox show 1 or more for messages and edtions, If you go beyond 999 you will see "+1k"

**Comment by stardiviner** [comment]
SEN did show that "1" red number when I test in `about:debugging`.
At second time I try to debug again, but when I click "Debug" on extension, it popup error in popup window:
```
Component returned failure code: 0x804b000d (NS_ERROR_CONNECTION_REFUSED) [nsIInputStream.available]
```
I tried both Firefox 47 and Firefox nightly 49. They both popup this error.

![screenshot_20180109_135710](https://user-images.githubusercontent.com/378699/34706860-0a524666-f545-11e7-8b95-92cd786de6a1.png)

**Comment by stardiviner** [comment]
I guess this is my Firefox issue, I tried "Debug" on other add-ons. Same error.

**Comment by brcontainer** [comment]
It's https://github.com/brcontainer/stack-exchange-notifications/issues/20#issuecomment-356188370 bug from FF specific version.

may be a bug even with linux version, Debug uses a local *"TCP port"* to communicate and probably failed to create port, can not communicate.

In Windows with Firefox 48 work fine.
